import '@testing-library/jest-dom/vitest'
import { cleanup } from '@testing-library/react'
import { afterEach, beforeAll, afterAll } from 'vitest'
import { server } from './src/mocks/server'

// Mock Wails Go bindings for desktop service tests
const mockStaff = {
  id: '01912345-6789-7abc-def0-123456789001',
  staff_code: 'STF001',
  full_name: 'Priya Sharma',
  phone: '9876543210',
  email: 'priya@example.com',
  gender: 'female',
  designation: 'stylist',
  joining_date: '2024-01-15',
  base_salary: 25000,
  commission_percentage: 10,
  status: 'active',
  created_at: '2024-01-15T00:00:00Z',
  updated_at: '2024-01-15T00:00:00Z',
}

const mockService = {
  id: '01912345-6789-7abc-def0-123456789002',
  service_code: 'SVC001',
  name: 'Haircut - Ladies',
  category: 'hair',
  description: 'Standard ladies haircut',
  duration_minutes: 45,
  price: 500,
  cost_price: 100,
  commission_type: 'percentage',
  commission_value: 10,
  status: 'active',
  created_at: '2024-01-15T00:00:00Z',
  updated_at: '2024-01-15T00:00:00Z',
}

const mockCustomer = {
  id: '01912345-6789-7abc-def0-123456789003',
  customer_code: 'CUS001',
  full_name: 'Anjali Desai',
  phone: '9876543211',
  email: 'anjali@example.com',
  gender: 'female',
  total_visits: 5,
  total_spent: 2500,
  status: 'active',
  created_at: '2024-01-15T00:00:00Z',
  updated_at: '2024-01-15T00:00:00Z',
}

const mockInvoice = {
  id: 'inv1',
  invoice_number: 'INV-001',
  customer_id: 'cust1',
  staff_id: 'staff1',
  items: [],
  subtotal: 2000,
  discount: 100,
  tax: 342,
  grand_total: 2242,
  payment_status: 'paid',
  payment_method: 'upi',
  notes: '',
  invoice_date: '2024-12-19',
  created_at: '2024-12-19T00:00:00Z',
  updated_at: '2024-12-19T00:00:00Z',
}

const mockExpense = {
  id: 'exp1',
  expense_number: 'EXP-001',
  category_id: 'cat1',
  category_name: 'Rent',
  amount: 25000,
  expense_date: '2024-12-01',
  payment_method: 'bank_transfer',
  vendor_name: 'Landlord',
  invoice_reference: '',
  description: 'Monthly rent',
  attachment_path: '',
  status: 'paid',
  created_by: '',
  created_at: '2024-12-01T00:00:00Z',
  updated_at: '2024-12-01T00:00:00Z',
}

const mockAdvance = {
  id: 'adv1',
  staff_id: 'staff2',
  staff_name: 'Rahul Kumar',
  amount: 5000,
  advance_date: '2024-12-10',
  reason: 'Personal',
  recovered_amount: 2000,
  remaining_amount: 3000,
  status: 'pending',
  created_at: '2024-12-10T00:00:00Z',
  updated_at: '2024-12-10T00:00:00Z',
}

const mockSalaryRecord = {
  id: 'sal1',
  salary_cycle_id: 'cyc1',
  staff_id: 'staff1',
  staff_name: 'Priya Sharma',
  base_salary: 25000,
  commission_amount: 5000,
  bonus_amount: 0,
  advance_amount: 2000,
  deduction_amount: 0,
  gross_salary: 30000,
  net_salary: 28000,
  payment_status: 'pending',
  payment_date: '',
  notes: '',
  created_at: '2024-12-01T00:00:00Z',
  updated_at: '2024-12-01T00:00:00Z',
}

;(globalThis as any).window = globalThis.window || {}
;(window as any).go = {
  main: {
    App: {
      GetVersion: async () => '0.2.0',
      GetEnvironment: async () => 'production',
    },
    StaffService: {
      ListStaff: async () => ({ staff: [mockStaff], page: 1, per_page: 20, total: 1, total_pages: 1 }),
      GetStaff: async () => mockStaff,
      CreateStaff: async () => mockStaff,
      UpdateStaff: async () => mockStaff,
      DeleteStaff: async () => {},
      GetStaffStats: async () => ({ total: 5, active: 4, inactive: 1, avg_salary: 20000 }),
    },
    ServiceService: {
      ListServices: async () => ({ services: [mockService], page: 1, per_page: 20, total: 1, total_pages: 1 }),
      GetService: async () => mockService,
      CreateService: async () => mockService,
      UpdateService: async () => mockService,
      DeleteService: async () => {},
      GetServiceStats: async () => ({ total: 10, active: 8, inactive: 2, avg_price: 750 }),
    },
    CustomerService: {
      ListCustomers: async () => ({ customers: [mockCustomer], page: 1, per_page: 20, total: 1, total_pages: 1 }),
      GetCustomer: async () => mockCustomer,
      CreateCustomer: async () => mockCustomer,
      UpdateCustomer: async () => mockCustomer,
      DeleteCustomer: async () => {},
      GetCustomerStats: async () => ({ total: 50, active: 45, inactive: 5, total_revenue: 125000, avg_visits: 5 }),
    },
    InvoiceService: {
      ListInvoices: async () => ({ invoices: [mockInvoice], page: 1, per_page: 20, total: 1, total_pages: 1 }),
      GetInvoice: async () => mockInvoice,
      CreateInvoice: async () => mockInvoice,
      RecordPayment: async () => ({ id: 'pay1', amount: 2242, method: 'upi' }),
      GetInvoiceStats: async () => ({ today_revenue: 12500, today_invoices: 8, avg_bill_value: 1562 }),
    },
    ExpenseService: {
      ListExpenses: async () => ({ expenses: [mockExpense], page: 1, per_page: 20, total: 1, total_pages: 1 }),
      GetExpense: async () => mockExpense,
      CreateExpense: async () => mockExpense,
      UpdateExpense: async () => mockExpense,
      DeleteExpense: async () => {},
      ListCategories: async () => [
        { id: 'cat1', name: 'Rent', description: 'Monthly rent', is_active: true, created_at: '2024-01-01T00:00:00Z', updated_at: '2024-01-01T00:00:00Z' },
        { id: 'cat2', name: 'Utilities', description: 'Electricity and water', is_active: true, created_at: '2024-01-01T00:00:00Z', updated_at: '2024-01-01T00:00:00Z' },
      ],
      CreateCategory: async () => ({ id: 'cat3', name: 'New', description: '' }),
      UpdateCategory: async () => ({ id: 'cat1', name: 'Rent', description: 'Monthly rent', is_active: true }),
      GetExpenseStats: async () => ({ today_expenses: 5000, monthly_expenses: 85000, today_revenue: 12500, monthly_revenue: 300000, monthly_profit: 215000, profit_margin: 71.7 }),
      GetExpenseReport: async () => ({ categories: [], total: 0 }),
      GetProfitLoss: async () => ({ revenue: 300000, expenses: 85000, salary_cost: 0, net_profit: 215000, margin: 71.7 }),
      GetMonthlyTrend: async () => [],
    },
    SalaryService: {
      ListSalaries: async () => [mockSalaryRecord],
      GetSalary: async () => mockSalaryRecord,
      GenerateSalary: async () => ({ message: 'Generated', records: [mockSalaryRecord] }),
      PaySalary: async () => {},
      ListCycles: async () => [{ id: 'cyc1', month: 6, year: 2026, status: 'generated', generated_at: '2024-12-01', created_at: '2024-12-01' }],
      CreateAdvance: async () => mockAdvance,
      ApproveAdvance: async () => ({ ...mockAdvance, status: 'approved' }),
      RejectAdvance: async () => ({ ...mockAdvance, status: 'rejected' }),
      ListAdvances: async () => ({ advances: [mockAdvance], page: 1, per_page: 20, total: 1, total_pages: 1 }),
      GetSalaryStats: async () => ({ total_payroll: 150000, pending_payments: 3, paid_salaries: 2, outstanding_advances: 10000 }),
    },
    PerformanceService: {
      GetPerformanceStats: async () => ({
        top_performer_today: { staff_id: '1', staff_name: 'Priya Sharma', revenue: 5000, customer_count: 3, invoice_count: 3, service_count: 5, avg_bill: 1667, commission: 500, rank: 1 },
        top_performer_month: { staff_id: '1', staff_name: 'Priya Sharma', revenue: 50000, customer_count: 30, invoice_count: 30, service_count: 50, avg_bill: 1667, commission: 5000, rank: 1 },
        total_revenue_today: 12500,
        total_customers_today: 8,
        avg_bill_today: 1562,
      }),
      GetRevenueTrend: async () => [
        { date: '2024-12-01', revenue: 10000 },
        { date: '2024-12-02', revenue: 12000 },
        { date: '2024-12-03', revenue: 8000 },
      ],
      GetTopPerformers: async () => [
        { staff_id: '1', staff_name: 'Priya Sharma', revenue: 50000, customer_count: 30, invoice_count: 30, service_count: 50, avg_bill: 1667, commission: 5000, rank: 1 },
        { staff_id: '2', staff_name: 'Rahul Kumar', revenue: 35000, customer_count: 20, invoice_count: 20, service_count: 35, avg_bill: 1750, commission: 3500, rank: 2 },
      ],
      GetDailyPerformance: async () => [],
      GetWeeklyPerformance: async () => [],
      GetMonthlyPerformance: async () => [],
      GetStaffPerformance: async () => [],
      GetStaffRevenueTrend: async () => [],
    },
    MembershipService: {
      ListPlans: async () => [{ id: 'plan1', name: 'Gold', plan_type: 'package', price: 5000, duration_days: 90, max_sessions: 12, is_active: true, services: [] }],
      GetPlan: async () => ({ id: 'plan1', name: 'Gold', plan_type: 'package', price: 5000, duration_days: 90, max_sessions: 12, is_active: true, services: [] }),
      CreatePlan: async () => {},
      UpdatePlan: async () => {},
      DeletePlan: async () => {},
      SellPlan: async () => ({ id: 'sub1', plan_id: 'plan1', customer_id: 'cust1', status: 'active' }),
      UseSession: async () => {},
      ListSubscriptions: async () => [[], 0],
      GetMembershipStats: async () => ({ total_plans: 3, active_subscriptions: 15, revenue: 75000, expiring_soon: 2, top_plan: 'Gold' }),
    },
    CommissionService: {
      CreateRule: async (input: any) => ({ id: 'rule1', ...input }),
      GetRule: async () => ({ id: 'rule1', rule_type: 'percentage', target_type: 'service', value: 10, is_active: true }),
      ListRules: async () => ({ rules: [{ id: 'rule1', rule_type: 'percentage', target_type: 'service', value: 10, is_active: true }], page: 1, per_page: 20, total: 1, total_pages: 1 }),
      UpdateRule: async (_id: any, input: any) => ({ id: 'rule1', ...input }),
      DeleteRule: async () => {},
      GetStaffCommission: async () => ({ staff_id: 'staff1', total: 5000, entries: [] }),
      GetMonthlyCommission: async () => ({ month: '2024-12', total: 15000, staff_commissions: [] }),
      GetCommissionStats: async () => ({ total_commission: 50000, pending: 5000, paid: 45000, staff_count: 4 }),
    },
    BackupService: {
      CreateBackup: async () => ({ id: 'bk1', backup_type: 'manual', file_path: '/backups/bk1.db', file_size: 1024, status: 'completed', created_at: '2024-12-19T00:00:00Z' }),
      VerifyBackup: async () => ({ valid: true, tables: 10, records: 500 }),
      RestoreBackup: async () => ({ id: 'rst1', backup_id: 'bk1', status: 'completed' }),
      ListBackups: async () => [[{ id: 'bk1', backup_type: 'manual', file_path: '/backups/bk1.db', file_size: 1024, status: 'completed', created_at: '2024-12-19T00:00:00Z' }], 1],
      ListRestores: async () => [[{ id: 'rst1', backup_id: 'bk1', status: 'completed' }], 1],
      GetBackupStats: async () => ({ total_backups: 5, last_backup: '2024-12-19T00:00:00Z', total_size: 5120, auto_backup_enabled: true }),
      DeleteBackup: async () => {},
    },
    AnalyticsService: {
      GetDashboard: async () => ({ today_revenue: 12500, today_customers: 8, today_invoices: 6, monthly_revenue: 300000 }),
      GetKPIs: async () => ({ revenue: 300000, customers: 50, invoices: 200, avg_bill: 1500 }),
      GetRevenueReport: async () => ({ total: 300000, data: [] }),
      GetCustomerReport: async () => ({ total_customers: 50, new_customers: 5, returning: 45, data: [] }),
      GetStaffReport: async () => ({ staff: [], total_revenue: 300000 }),
      GetServiceReport: async () => ({ services: [], total_revenue: 300000 }),
      GetExpenseAnalytics: async () => ({ total: 85000, categories: [], data: [] }),
      GetInventoryReport: async () => ({ total_products: 30, low_stock: 5, total_value: 50000 }),
      GetProfitLossReport: async () => ({ revenue: 300000, expenses: 85000, net_profit: 215000, data: [] }),
    },
    AppointmentService: {
      CreateAppointment: async () => {},
      UpdateAppointment: async () => {},
      UpdateAppointmentStatus: async () => {},
      DeleteAppointment: async () => {},
      GetAppointment: async () => ({ id: 'apt1', customer_id: 'cust1', staff_id: 'staff1', appointment_date: '2024-12-20', start_time: '10:00', end_time: '11:00', status: 'booked', notes: '', is_walkin: false, total_amount: 500, services: [] }),
      ListAppointments: async () => [[{ id: 'apt1', customer_id: 'cust1', staff_id: 'staff1', appointment_date: '2024-12-20', start_time: '10:00', end_time: '11:00', status: 'booked', notes: '', is_walkin: false, total_amount: 500, services: [] }], 1],
      GetAppointmentHistory: async () => [{ id: 'hist1', action: 'created', timestamp: '2024-12-19T00:00:00Z' }],
    },
    WhatsAppService: {
      CreateTemplate: async () => {},
      UpdateTemplate: async () => {},
      DeleteTemplate: async () => {},
      ListTemplates: async () => [{ id: 'tpl1', name: 'Welcome', category: 'general', body: 'Hello {{name}}!', is_active: true }],
      SendMessage: async () => ({ id: 'msg1', template_id: 'tpl1', phone: '9876543210', status: 'sent' }),
      ListMessages: async () => [[{ id: 'msg1', template_id: 'tpl1', phone: '9876543210', status: 'sent' }], 1],
      GetWhatsAppStats: async () => ({ total_sent: 100, delivered: 95, read: 80, failed: 3, queued: 2 }),
      CreateRule: async () => {},
      UpdateRule: async () => {},
      DeleteRule: async () => {},
      ListRules: async () => [{ id: 'rule1', name: 'Birthday', trigger: 'birthday', template_id: 'tpl1', is_active: true }],
    },
    GSTService: {
      GetSettings: async () => ({ gstin: '27AABCU9603R1ZM', business_name: 'Salon', state_code: '27', is_enabled: true }),
      SaveSettings: async () => {},
      ListTaxRates: async () => [{ id: 'tax1', name: 'GST 18%', rate: 18, category: 'service', is_active: true }],
      CreateTaxRate: async () => {},
      UpdateTaxRate: async () => {},
      DeleteTaxRate: async () => {},
      GetReport: async () => ({ total_taxable: 250000, total_cgst: 22500, total_sgst: 22500, total_igst: 0, entries: [] }),
    },
    CloudBackupService: {
      GetConfig: async () => ({ provider: 'google_drive', auto_backup: true, frequency: 'daily' }),
      SaveConfig: async () => {},
      TestConnection: async () => {},
      BackupNow: async () => ({ id: 'cbk1', provider: 'google_drive', status: 'completed', created_at: '2024-12-19T00:00:00Z' }),
      Restore: async () => {},
      ListHistory: async () => [[{ id: 'cbk1', provider: 'google_drive', status: 'completed', created_at: '2024-12-19T00:00:00Z' }], 1],
      GetCloudBackupStats: async () => ({ total_backups: 10, last_backup: '2024-12-19T00:00:00Z', storage_used: 10240 }),
    },
    PrinterService: {
      GetSettings: async () => ({ printer_name: 'POS-80', paper_width: 80, auto_print: false }),
      SaveSettings: async () => {},
      PrintInvoice: async () => [{ id: 'job1', status: 'completed', printer: 'POS-80' }, '<html>Invoice</html>'],
      PrintReceipt: async () => [{ id: 'job2', status: 'completed', printer: 'POS-80' }, { lines: [] }],
      PrintTest: async () => [{ id: 'job3', status: 'completed', printer: 'POS-80' }, { lines: ['Test'] }],
      ListPrintJobs: async () => [[{ id: 'job1', status: 'completed', printer: 'POS-80' }], 1],
      GetPrintJob: async () => ({ id: 'job1', status: 'completed', printer: 'POS-80' }),
    },
    ProductService: {
      ListProducts: async () => ({ products: [{ id: 'prod1', name: 'Shampoo', sku: 'SHP001', category: 'hair', price: 500, stock_quantity: 20, reorder_level: 5, status: 'active' }], page: 1, per_page: 20, total: 1, total_pages: 1 }),
      GetProduct: async () => ({ id: 'prod1', name: 'Shampoo', sku: 'SHP001', category: 'hair', price: 500, stock_quantity: 20, reorder_level: 5, status: 'active' }),
      CreateProduct: async () => ({ id: 'prod1', name: 'Shampoo', sku: 'SHP001' }),
      UpdateProduct: async () => ({ id: 'prod1', name: 'Shampoo Updated' }),
      DeleteProduct: async () => {},
      AdjustStock: async () => ({ id: 'txn1', product_id: 'prod1', quantity: 5, transaction_type: 'purchase' }),
      ListStockHistory: async () => ({ transactions: [{ id: 'txn1', product_id: 'prod1', quantity: 5, transaction_type: 'purchase' }], page: 1, per_page: 20, total: 1, total_pages: 1 }),
      CreatePurchase: async () => ({ id: 'pur1', product_id: 'prod1', quantity: 50, total_cost: 5000 }),
      ListPurchases: async () => ({ purchases: [{ id: 'pur1', product_id: 'prod1', quantity: 50, total_cost: 5000 }], page: 1, per_page: 20, total: 1, total_pages: 1 }),
      GetInventoryStats: async () => ({ total_products: 30, low_stock: 5, out_of_stock: 1, total_value: 50000 }),
      GetLowStockProducts: async () => [{ id: 'prod2', name: 'Conditioner', stock_quantity: 2, reorder_level: 5 }],
    },
    LicenseService: {
      GetStatus: async () => ({ status: 'active', expires_at: '2025-12-31', plan: 'professional' }),
      Validate: async () => ({ valid: true, message: 'License is valid' }),
      Activate: async () => ({ id: 'lic1', key: 'XXXX-XXXX', status: 'active' }),
      Renew: async () => ({ id: 'lic1', key: 'XXXX-XXXX', status: 'active', expires_at: '2026-12-31' }),
      ListEvents: async () => [[{ id: 'evt1', event_type: 'activation', created_at: '2024-01-01T00:00:00Z' }], 1],
    },
    ImportService: {
      Upload: async () => [{ id: 'imp1', file_name: 'data.csv', status: 'uploaded' }, ['Name', 'Phone', 'Email'], [{ source: 'Name', target: 'full_name' }]],
      Validate: async () => ({ valid_rows: 10, invalid_rows: 0, errors: [] }),
      Process: async () => ({ id: 'imp1', status: 'completed', records_processed: 10 }),
      ListJobs: async () => [[{ id: 'imp1', file_name: 'data.csv', status: 'completed' }], 1],
      GetJob: async () => ({ id: 'imp1', file_name: 'data.csv', status: 'completed' }),
      ListLogs: async () => [[{ id: 'log1', job_id: 'imp1', status: 'success', message: 'Imported row 1' }], 1],
    },
    UpdateService: {
      CheckForUpdate: async () => ({ available: true, version: '0.3.0', release_notes: 'Bug fixes' }),
      DownloadUpdate: async () => ({ id: 'upd1', version: '0.3.0', status: 'downloaded' }),
      InstallUpdate: async () => ({ id: 'upd1', version: '0.3.0', status: 'installed' }),
      GetUpdateStatus: async () => ({ available: false, current_version: '0.2.0' }),
      ListUpdateHistory: async () => [[{ id: 'upd1', version: '0.2.0', status: 'installed', installed_at: '2024-12-01T00:00:00Z' }], 1],
    },
  },
}

beforeAll(() => server.listen({ onUnhandledRequest: 'warn' }))
afterEach(() => {
  cleanup()
  server.resetHandlers()
})
afterAll(() => server.close())
