// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';
import {context} from '../models';

export function GetCustomerReport(arg1:string,arg2:string):Promise<domain.CustomerReport>;

export function GetDashboard():Promise<domain.DashboardStats>;

export function GetExpenseAnalytics(arg1:string,arg2:string):Promise<domain.ExpenseReport>;

export function GetInventoryReport():Promise<domain.InventoryReport>;

export function GetKPIs(arg1:string,arg2:string):Promise<domain.KPIMetrics>;

export function GetProfitLossReport(arg1:string,arg2:string,arg3:string):Promise<domain.ProfitLossReport>;

export function GetRevenueReport(arg1:string,arg2:string,arg3:string):Promise<domain.RevenueReport>;

export function GetServiceReport(arg1:string,arg2:string):Promise<domain.ServiceReport>;

export function GetStaffReport(arg1:string,arg2:string):Promise<domain.StaffReport>;

export function SetContext(arg1:context.Context):Promise<void>;
