// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCustomerReport(arg1, arg2) {
  return window['go']['main']['AnalyticsService']['GetCustomerReport'](arg1, arg2);
}

export function GetDashboard() {
  return window['go']['main']['AnalyticsService']['GetDashboard']();
}

export function GetExpenseAnalytics(arg1, arg2) {
  return window['go']['main']['AnalyticsService']['GetExpenseAnalytics'](arg1, arg2);
}

export function GetInventoryReport() {
  return window['go']['main']['AnalyticsService']['GetInventoryReport']();
}

export function GetKPIs(arg1, arg2) {
  return window['go']['main']['AnalyticsService']['GetKPIs'](arg1, arg2);
}

export function GetProfitLossReport(arg1, arg2, arg3) {
  return window['go']['main']['AnalyticsService']['GetProfitLossReport'](arg1, arg2, arg3);
}

export function GetRevenueReport(arg1, arg2, arg3) {
  return window['go']['main']['AnalyticsService']['GetRevenueReport'](arg1, arg2, arg3);
}

export function GetServiceReport(arg1, arg2) {
  return window['go']['main']['AnalyticsService']['GetServiceReport'](arg1, arg2);
}

export function GetStaffReport(arg1, arg2) {
  return window['go']['main']['AnalyticsService']['GetStaffReport'](arg1, arg2);
}

export function SetContext(arg1) {
  return window['go']['main']['AnalyticsService']['SetContext'](arg1);
}
