// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetEnvironment() {
  return window['go']['main']['App']['GetEnvironment']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}
