// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';
import {context} from '../models';

export function CreateAppointment(arg1:domain.Appointment,arg2:Array<domain.AppointmentService>):Promise<void>;

export function DeleteAppointment(arg1:string):Promise<void>;

export function GetAppointment(arg1:string):Promise<domain.Appointment>;

export function GetAppointmentHistory(arg1:string):Promise<Array<domain.AppointmentHistory>>;

export function ListAppointments(arg1:domain.AppointmentFilter):Promise<Array<domain.Appointment>>;

export function SetContext(arg1:context.Context):Promise<void>;

export function UpdateAppointment(arg1:domain.Appointment,arg2:Array<domain.AppointmentService>):Promise<void>;

export function UpdateAppointmentStatus(arg1:string,arg2:string,arg3:string):Promise<void>;
