// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateAppointment(arg1, arg2) {
  return window['go']['main']['AppointmentService']['CreateAppointment'](arg1, arg2);
}

export function DeleteAppointment(arg1) {
  return window['go']['main']['AppointmentService']['DeleteAppointment'](arg1);
}

export function GetAppointment(arg1) {
  return window['go']['main']['AppointmentService']['GetAppointment'](arg1);
}

export function GetAppointmentHistory(arg1) {
  return window['go']['main']['AppointmentService']['GetAppointmentHistory'](arg1);
}

export function ListAppointments(arg1) {
  return window['go']['main']['AppointmentService']['ListAppointments'](arg1);
}

export function SetContext(arg1) {
  return window['go']['main']['AppointmentService']['SetContext'](arg1);
}

export function UpdateAppointment(arg1, arg2) {
  return window['go']['main']['AppointmentService']['UpdateAppointment'](arg1, arg2);
}

export function UpdateAppointmentStatus(arg1, arg2, arg3) {
  return window['go']['main']['AppointmentService']['UpdateAppointmentStatus'](arg1, arg2, arg3);
}
