// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';
import {context} from '../models';

export function CreateBackup(arg1:string):Promise<domain.BackupRecord>;

export function DeleteBackup(arg1:string):Promise<void>;

export function GetBackupStats():Promise<domain.BackupStats>;

export function ListBackups(arg1:number,arg2:number):Promise<Array<domain.BackupRecord>>;

export function ListRestores(arg1:number,arg2:number):Promise<Array<domain.RestoreRecord>>;

export function RestoreBackup(arg1:string,arg2:string):Promise<domain.RestoreRecord>;

export function SetContext(arg1:context.Context):Promise<void>;

export function VerifyBackup(arg1:string):Promise<domain.BackupVerification>;
