// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateBackup(arg1) {
  return window['go']['main']['BackupService']['CreateBackup'](arg1);
}

export function DeleteBackup(arg1) {
  return window['go']['main']['BackupService']['DeleteBackup'](arg1);
}

export function GetBackupStats() {
  return window['go']['main']['BackupService']['GetBackupStats']();
}

export function ListBackups(arg1, arg2) {
  return window['go']['main']['BackupService']['ListBackups'](arg1, arg2);
}

export function ListRestores(arg1, arg2) {
  return window['go']['main']['BackupService']['ListRestores'](arg1, arg2);
}

export function RestoreBackup(arg1, arg2) {
  return window['go']['main']['BackupService']['RestoreBackup'](arg1, arg2);
}

export function SetContext(arg1) {
  return window['go']['main']['BackupService']['SetContext'](arg1);
}

export function VerifyBackup(arg1) {
  return window['go']['main']['BackupService']['VerifyBackup'](arg1);
}
