// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';
import {context} from '../models';

export function BackupNow():Promise<domain.CloudBackupHistory>;

export function GetCloudBackupStats():Promise<domain.CloudBackupStats>;

export function GetConfig():Promise<domain.CloudBackupConfig>;

export function ListHistory(arg1:number,arg2:number):Promise<Array<domain.CloudBackupHistory>>;

export function Restore(arg1:string):Promise<void>;

export function SaveConfig(arg1:domain.CloudBackupConfig):Promise<void>;

export function SetContext(arg1:context.Context):Promise<void>;

export function TestConnection():Promise<void>;
