// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BackupNow() {
  return window['go']['main']['CloudBackupService']['BackupNow']();
}

export function GetCloudBackupStats() {
  return window['go']['main']['CloudBackupService']['GetCloudBackupStats']();
}

export function GetConfig() {
  return window['go']['main']['CloudBackupService']['GetConfig']();
}

export function ListHistory(arg1, arg2) {
  return window['go']['main']['CloudBackupService']['ListHistory'](arg1, arg2);
}

export function Restore(arg1) {
  return window['go']['main']['CloudBackupService']['Restore'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['CloudBackupService']['SaveConfig'](arg1);
}

export function SetContext(arg1) {
  return window['go']['main']['CloudBackupService']['SetContext'](arg1);
}

export function TestConnection() {
  return window['go']['main']['CloudBackupService']['TestConnection']();
}
