// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {usecase} from '../models';
import {domain} from '../models';
import {ports} from '../models';
import {context} from '../models';

export function CreateRule(arg1:usecase.CreateRuleInput):Promise<domain.CommissionRule>;

export function DeleteRule(arg1:string):Promise<void>;

export function GetCommissionStats():Promise<usecase.CommissionStats>;

export function GetMonthlyCommission(arg1:usecase.MonthlyCommissionInput):Promise<Array<ports.CommissionStaffSummary>>;

export function GetRule(arg1:string):Promise<domain.CommissionRule>;

export function GetStaffCommission(arg1:usecase.GetStaffCommissionInput):Promise<usecase.StaffCommissionOutput>;

export function ListRules(arg1:usecase.ListRulesInput):Promise<usecase.ListRulesOutput>;

export function SetContext(arg1:context.Context):Promise<void>;

export function UpdateRule(arg1:string,arg2:usecase.UpdateRuleInput):Promise<domain.CommissionRule>;
