// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateRule(arg1) {
  return window['go']['main']['CommissionService']['CreateRule'](arg1);
}

export function DeleteRule(arg1) {
  return window['go']['main']['CommissionService']['DeleteRule'](arg1);
}

export function GetCommissionStats() {
  return window['go']['main']['CommissionService']['GetCommissionStats']();
}

export function GetMonthlyCommission(arg1) {
  return window['go']['main']['CommissionService']['GetMonthlyCommission'](arg1);
}

export function GetRule(arg1) {
  return window['go']['main']['CommissionService']['GetRule'](arg1);
}

export function GetStaffCommission(arg1) {
  return window['go']['main']['CommissionService']['GetStaffCommission'](arg1);
}

export function ListRules(arg1) {
  return window['go']['main']['CommissionService']['ListRules'](arg1);
}

export function SetContext(arg1) {
  return window['go']['main']['CommissionService']['SetContext'](arg1);
}

export function UpdateRule(arg1, arg2) {
  return window['go']['main']['CommissionService']['UpdateRule'](arg1, arg2);
}
