// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateCustomer(arg1) {
  return window['go']['main']['CustomerService']['CreateCustomer'](arg1);
}

export function DeleteCustomer(arg1) {
  return window['go']['main']['CustomerService']['DeleteCustomer'](arg1);
}

export function GetCustomer(arg1) {
  return window['go']['main']['CustomerService']['GetCustomer'](arg1);
}

export function GetCustomerStats() {
  return window['go']['main']['CustomerService']['GetCustomerStats']();
}

export function ListCustomers(arg1) {
  return window['go']['main']['CustomerService']['ListCustomers'](arg1);
}

export function SetContext(arg1) {
  return window['go']['main']['CustomerService']['SetContext'](arg1);
}

export function UpdateCustomer(arg1, arg2) {
  return window['go']['main']['CustomerService']['UpdateCustomer'](arg1, arg2);
}
