// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {usecase} from '../models';
import {domain} from '../models';
import {context} from '../models';

export function CreateCustomer(arg1:usecase.CreateCustomerInput):Promise<domain.Customer>;

export function DeleteCustomer(arg1:string):Promise<void>;

export function GetCustomer(arg1:string):Promise<domain.Customer>;

export function GetCustomerStats():Promise<usecase.CustomerStats>;

export function ListCustomers(arg1:usecase.ListCustomerInput):Promise<usecase.ListCustomerOutput>;

export function SetContext(arg1:context.Context):Promise<void>;

export function UpdateCustomer(arg1:string,arg2:usecase.UpdateCustomerInput):Promise<domain.Customer>;
