// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';
import {usecase} from '../models';
import {context} from '../models';

export function CreateCategory(arg1:string,arg2:string):Promise<domain.ExpenseCategory>;

export function CreateExpense(arg1:usecase.CreateExpenseInput):Promise<domain.Expense>;

export function DeleteExpense(arg1:string):Promise<void>;

export function GetExpense(arg1:string):Promise<domain.Expense>;

export function GetExpenseReport(arg1:usecase.ExpenseReportInput):Promise<usecase.ExpenseReport>;

export function GetExpenseStats():Promise<domain.ExpenseStats>;

export function GetMonthlyTrend(arg1:number):Promise<Array<domain.MonthlyTrend>>;

export function GetProfitLoss(arg1:usecase.ProfitLossInput):Promise<domain.ProfitLoss>;

export function ListCategories(arg1:boolean):Promise<Array<domain.ExpenseCategory>>;

export function ListExpenses(arg1:usecase.ListExpensesInput):Promise<usecase.ListExpensesOutput>;

export function SetContext(arg1:context.Context):Promise<void>;

export function UpdateCategory(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<domain.ExpenseCategory>;

export function UpdateExpense(arg1:string,arg2:usecase.UpdateExpenseInput):Promise<domain.Expense>;
