// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateCategory(arg1, arg2) {
  return window['go']['main']['ExpenseService']['CreateCategory'](arg1, arg2);
}

export function CreateExpense(arg1) {
  return window['go']['main']['ExpenseService']['CreateExpense'](arg1);
}

export function DeleteExpense(arg1) {
  return window['go']['main']['ExpenseService']['DeleteExpense'](arg1);
}

export function GetExpense(arg1) {
  return window['go']['main']['ExpenseService']['GetExpense'](arg1);
}

export function GetExpenseReport(arg1) {
  return window['go']['main']['ExpenseService']['GetExpenseReport'](arg1);
}

export function GetExpenseStats() {
  return window['go']['main']['ExpenseService']['GetExpenseStats']();
}

export function GetMonthlyTrend(arg1) {
  return window['go']['main']['ExpenseService']['GetMonthlyTrend'](arg1);
}

export function GetProfitLoss(arg1) {
  return window['go']['main']['ExpenseService']['GetProfitLoss'](arg1);
}

export function ListCategories(arg1) {
  return window['go']['main']['ExpenseService']['ListCategories'](arg1);
}

export function ListExpenses(arg1) {
  return window['go']['main']['ExpenseService']['ListExpenses'](arg1);
}

export function SetContext(arg1) {
  return window['go']['main']['ExpenseService']['SetContext'](arg1);
}

export function UpdateCategory(arg1, arg2, arg3, arg4) {
  return window['go']['main']['ExpenseService']['UpdateCategory'](arg1, arg2, arg3, arg4);
}

export function UpdateExpense(arg1, arg2) {
  return window['go']['main']['ExpenseService']['UpdateExpense'](arg1, arg2);
}
