// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';
import {context} from '../models';

export function CreateTaxRate(arg1:domain.TaxRate):Promise<void>;

export function DeleteTaxRate(arg1:string):Promise<void>;

export function GetReport(arg1:domain.GSTReportFilter):Promise<domain.GSTReport>;

export function GetSettings():Promise<domain.GSTSettings>;

export function ListTaxRates(arg1:string):Promise<Array<domain.TaxRate>>;

export function SaveSettings(arg1:domain.GSTSettings):Promise<void>;

export function SetContext(arg1:context.Context):Promise<void>;

export function UpdateTaxRate(arg1:domain.TaxRate):Promise<void>;
