// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateTaxRate(arg1) {
  return window['go']['main']['GSTService']['CreateTaxRate'](arg1);
}

export function DeleteTaxRate(arg1) {
  return window['go']['main']['GSTService']['DeleteTaxRate'](arg1);
}

export function GetReport(arg1) {
  return window['go']['main']['GSTService']['GetReport'](arg1);
}

export function GetSettings() {
  return window['go']['main']['GSTService']['GetSettings']();
}

export function ListTaxRates(arg1) {
  return window['go']['main']['GSTService']['ListTaxRates'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['GSTService']['SaveSettings'](arg1);
}

export function SetContext(arg1) {
  return window['go']['main']['GSTService']['SetContext'](arg1);
}

export function UpdateTaxRate(arg1) {
  return window['go']['main']['GSTService']['UpdateTaxRate'](arg1);
}
