// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';
import {context} from '../models';

export function GetJob(arg1:string):Promise<domain.ImportJob>;

export function ListJobs(arg1:number,arg2:number):Promise<Array<domain.ImportJob>>;

export function ListLogs(arg1:string,arg2:string,arg3:number,arg4:number):Promise<Array<domain.ImportLog>>;

export function Process(arg1:string):Promise<domain.ImportJob>;

export function SetContext(arg1:context.Context):Promise<void>;

export function Upload(arg1:string,arg2:string,arg3:string):Promise<domain.ImportJob>;

export function Validate(arg1:string,arg2:Array<domain.ColumnMapping>):Promise<domain.ImportPreview>;
