// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetJob(arg1) {
  return window['go']['main']['ImportService']['GetJob'](arg1);
}

export function ListJobs(arg1, arg2) {
  return window['go']['main']['ImportService']['ListJobs'](arg1, arg2);
}

export function ListLogs(arg1, arg2, arg3, arg4) {
  return window['go']['main']['ImportService']['ListLogs'](arg1, arg2, arg3, arg4);
}

export function Process(arg1) {
  return window['go']['main']['ImportService']['Process'](arg1);
}

export function SetContext(arg1) {
  return window['go']['main']['ImportService']['SetContext'](arg1);
}

export function Upload(arg1, arg2, arg3) {
  return window['go']['main']['ImportService']['Upload'](arg1, arg2, arg3);
}

export function Validate(arg1, arg2) {
  return window['go']['main']['ImportService']['Validate'](arg1, arg2);
}
