// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {usecase} from '../models';
import {domain} from '../models';
import {context} from '../models';

export function CreateInvoice(arg1:usecase.CreateInvoiceInput):Promise<domain.Invoice>;

export function GetInvoice(arg1:string):Promise<domain.Invoice>;

export function GetInvoiceStats():Promise<usecase.InvoiceStats>;

export function ListInvoices(arg1:usecase.ListInvoiceInput):Promise<usecase.ListInvoiceOutput>;

export function RecordPayment(arg1:string,arg2:usecase.RecordPaymentInput):Promise<domain.Payment>;

export function SetContext(arg1:context.Context):Promise<void>;
