// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateInvoice(arg1) {
  return window['go']['main']['InvoiceService']['CreateInvoice'](arg1);
}

export function GetInvoice(arg1) {
  return window['go']['main']['InvoiceService']['GetInvoice'](arg1);
}

export function GetInvoiceStats() {
  return window['go']['main']['InvoiceService']['GetInvoiceStats']();
}

export function ListInvoices(arg1) {
  return window['go']['main']['InvoiceService']['ListInvoices'](arg1);
}

export function RecordPayment(arg1, arg2) {
  return window['go']['main']['InvoiceService']['RecordPayment'](arg1, arg2);
}

export function SetContext(arg1) {
  return window['go']['main']['InvoiceService']['SetContext'](arg1);
}
