// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';
import {context} from '../models';

export function Activate(arg1:string,arg2:string,arg3:string):Promise<domain.License>;

export function GetStatus():Promise<domain.LicenseStatus>;

export function ListEvents(arg1:number,arg2:number):Promise<Array<domain.LicenseEvent>>;

export function Renew(arg1:string):Promise<domain.License>;

export function SetContext(arg1:context.Context):Promise<void>;

export function Validate():Promise<domain.LicenseValidation>;
