// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Activate(arg1, arg2, arg3) {
  return window['go']['main']['LicenseService']['Activate'](arg1, arg2, arg3);
}

export function GetStatus() {
  return window['go']['main']['LicenseService']['GetStatus']();
}

export function ListEvents(arg1, arg2) {
  return window['go']['main']['LicenseService']['ListEvents'](arg1, arg2);
}

export function Renew(arg1) {
  return window['go']['main']['LicenseService']['Renew'](arg1);
}

export function SetContext(arg1) {
  return window['go']['main']['LicenseService']['SetContext'](arg1);
}

export function Validate() {
  return window['go']['main']['LicenseService']['Validate']();
}
