// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';
import {context} from '../models';

export function CreatePlan(arg1:domain.MembershipPlan,arg2:Array<domain.PackageService>):Promise<void>;

export function DeletePlan(arg1:string):Promise<void>;

export function GetMembershipStats():Promise<domain.MembershipStats>;

export function GetPlan(arg1:string):Promise<domain.MembershipPlan>;

export function ListPlans(arg1:string):Promise<Array<domain.MembershipPlan>>;

export function ListSubscriptions(arg1:string,arg2:string,arg3:number,arg4:number):Promise<Array<domain.MemberSubscription>>;

export function SellPlan(arg1:string,arg2:string,arg3:number):Promise<domain.MemberSubscription>;

export function SetContext(arg1:context.Context):Promise<void>;

export function UpdatePlan(arg1:domain.MembershipPlan,arg2:Array<domain.PackageService>):Promise<void>;

export function UseSession(arg1:string):Promise<void>;
