// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreatePlan(arg1, arg2) {
  return window['go']['main']['MembershipService']['CreatePlan'](arg1, arg2);
}

export function DeletePlan(arg1) {
  return window['go']['main']['MembershipService']['DeletePlan'](arg1);
}

export function GetMembershipStats() {
  return window['go']['main']['MembershipService']['GetMembershipStats']();
}

export function GetPlan(arg1) {
  return window['go']['main']['MembershipService']['GetPlan'](arg1);
}

export function ListPlans(arg1) {
  return window['go']['main']['MembershipService']['ListPlans'](arg1);
}

export function ListSubscriptions(arg1, arg2, arg3, arg4) {
  return window['go']['main']['MembershipService']['ListSubscriptions'](arg1, arg2, arg3, arg4);
}

export function SellPlan(arg1, arg2, arg3) {
  return window['go']['main']['MembershipService']['SellPlan'](arg1, arg2, arg3);
}

export function SetContext(arg1) {
  return window['go']['main']['MembershipService']['SetContext'](arg1);
}

export function UpdatePlan(arg1, arg2) {
  return window['go']['main']['MembershipService']['UpdatePlan'](arg1, arg2);
}

export function UseSession(arg1) {
  return window['go']['main']['MembershipService']['UseSession'](arg1);
}
