// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {usecase} from '../models';
import {domain} from '../models';
import {context} from '../models';

export function GetDailyPerformance(arg1:usecase.DailyPerformanceInput):Promise<Array<domain.StaffPerformanceSummary>>;

export function GetMonthlyPerformance(arg1:usecase.PeriodPerformanceInput):Promise<Array<domain.StaffPerformanceSummary>>;

export function GetPerformanceStats():Promise<usecase.PerformanceStats>;

export function GetRevenueTrend(arg1:string,arg2:string):Promise<Array<domain.RevenueTrendPoint>>;

export function GetStaffPerformance(arg1:string,arg2:string,arg3:string):Promise<Array<domain.StaffPerformanceDaily>>;

export function GetStaffRevenueTrend(arg1:string,arg2:string,arg3:string):Promise<Array<domain.RevenueTrendPoint>>;

export function GetTopPerformers(arg1:usecase.TopPerformersInput):Promise<Array<domain.StaffPerformanceSummary>>;

export function GetWeeklyPerformance(arg1:usecase.PeriodPerformanceInput):Promise<Array<domain.StaffPerformanceSummary>>;

export function SetContext(arg1:context.Context):Promise<void>;
