// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDailyPerformance(arg1) {
  return window['go']['main']['PerformanceService']['GetDailyPerformance'](arg1);
}

export function GetMonthlyPerformance(arg1) {
  return window['go']['main']['PerformanceService']['GetMonthlyPerformance'](arg1);
}

export function GetPerformanceStats() {
  return window['go']['main']['PerformanceService']['GetPerformanceStats']();
}

export function GetRevenueTrend(arg1, arg2) {
  return window['go']['main']['PerformanceService']['GetRevenueTrend'](arg1, arg2);
}

export function GetStaffPerformance(arg1, arg2, arg3) {
  return window['go']['main']['PerformanceService']['GetStaffPerformance'](arg1, arg2, arg3);
}

export function GetStaffRevenueTrend(arg1, arg2, arg3) {
  return window['go']['main']['PerformanceService']['GetStaffRevenueTrend'](arg1, arg2, arg3);
}

export function GetTopPerformers(arg1) {
  return window['go']['main']['PerformanceService']['GetTopPerformers'](arg1);
}

export function GetWeeklyPerformance(arg1) {
  return window['go']['main']['PerformanceService']['GetWeeklyPerformance'](arg1);
}

export function SetContext(arg1) {
  return window['go']['main']['PerformanceService']['SetContext'](arg1);
}
