// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';
import {context} from '../models';

export function GetPrintJob(arg1:string):Promise<domain.PrintJob>;

export function GetSettings():Promise<domain.PrinterSettings>;

export function ListPrintJobs(arg1:number,arg2:number):Promise<Array<domain.PrintJob>>;

export function PrintInvoice(arg1:domain.ReceiptData):Promise<domain.PrintJob>;

export function PrintReceipt(arg1:domain.ReceiptData):Promise<domain.PrintJob>;

export function PrintTest():Promise<domain.PrintJob>;

export function SaveSettings(arg1:domain.PrinterSettings):Promise<void>;

export function SetContext(arg1:context.Context):Promise<void>;
