// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetPrintJob(arg1) {
  return window['go']['main']['PrinterService']['GetPrintJob'](arg1);
}

export function GetSettings() {
  return window['go']['main']['PrinterService']['GetSettings']();
}

export function ListPrintJobs(arg1, arg2) {
  return window['go']['main']['PrinterService']['ListPrintJobs'](arg1, arg2);
}

export function PrintInvoice(arg1) {
  return window['go']['main']['PrinterService']['PrintInvoice'](arg1);
}

export function PrintReceipt(arg1) {
  return window['go']['main']['PrinterService']['PrintReceipt'](arg1);
}

export function PrintTest() {
  return window['go']['main']['PrinterService']['PrintTest']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['PrinterService']['SaveSettings'](arg1);
}

export function SetContext(arg1) {
  return window['go']['main']['PrinterService']['SetContext'](arg1);
}
