// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AdjustStock(arg1) {
  return window['go']['main']['ProductService']['AdjustStock'](arg1);
}

export function CreateProduct(arg1) {
  return window['go']['main']['ProductService']['CreateProduct'](arg1);
}

export function CreatePurchase(arg1) {
  return window['go']['main']['ProductService']['CreatePurchase'](arg1);
}

export function DeleteProduct(arg1) {
  return window['go']['main']['ProductService']['DeleteProduct'](arg1);
}

export function GetInventoryStats() {
  return window['go']['main']['ProductService']['GetInventoryStats']();
}

export function GetLowStockProducts() {
  return window['go']['main']['ProductService']['GetLowStockProducts']();
}

export function GetProduct(arg1) {
  return window['go']['main']['ProductService']['GetProduct'](arg1);
}

export function GetPurchase(arg1) {
  return window['go']['main']['ProductService']['GetPurchase'](arg1);
}

export function ListProducts(arg1) {
  return window['go']['main']['ProductService']['ListProducts'](arg1);
}

export function ListPurchases(arg1) {
  return window['go']['main']['ProductService']['ListPurchases'](arg1);
}

export function ListStockHistory(arg1) {
  return window['go']['main']['ProductService']['ListStockHistory'](arg1);
}

export function SetContext(arg1) {
  return window['go']['main']['ProductService']['SetContext'](arg1);
}

export function UpdateProduct(arg1, arg2) {
  return window['go']['main']['ProductService']['UpdateProduct'](arg1, arg2);
}
