// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {usecase} from '../models';
import {domain} from '../models';
import {context} from '../models';

export function AdjustStock(arg1:usecase.StockAdjustInput):Promise<domain.StockTransaction>;

export function CreateProduct(arg1:usecase.CreateProductInput):Promise<domain.Product>;

export function CreatePurchase(arg1:usecase.CreatePurchaseInput):Promise<domain.PurchaseEntry>;

export function DeleteProduct(arg1:string):Promise<void>;

export function GetInventoryStats():Promise<domain.InventoryStats>;

export function GetLowStockProducts():Promise<Array<domain.LowStockItem>>;

export function GetProduct(arg1:string):Promise<domain.Product>;

export function GetPurchase(arg1:string):Promise<domain.PurchaseEntry>;

export function ListProducts(arg1:usecase.ListProductsInput):Promise<usecase.ListProductsOutput>;

export function ListPurchases(arg1:usecase.ListPurchasesInput):Promise<usecase.ListPurchasesOutput>;

export function ListStockHistory(arg1:usecase.ListStockHistoryInput):Promise<usecase.ListStockHistoryOutput>;

export function SetContext(arg1:context.Context):Promise<void>;

export function UpdateProduct(arg1:string,arg2:usecase.UpdateProductInput):Promise<domain.Product>;
