// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';
import {usecase} from '../models';
import {context} from '../models';

export function ApproveAdvance(arg1:string):Promise<domain.Advance>;

export function CreateAdvance(arg1:usecase.CreateAdvanceInput):Promise<domain.Advance>;

export function GenerateSalary(arg1:usecase.GenerateSalaryInput):Promise<usecase.GenerateSalaryOutput>;

export function GetSalary(arg1:string):Promise<domain.SalaryRecord>;

export function GetSalaryStats():Promise<usecase.SalaryStats>;

export function ListAdvances(arg1:usecase.ListAdvancesInput):Promise<usecase.ListAdvancesOutput>;

export function ListCycles(arg1:number):Promise<Array<domain.SalaryCycle>>;

export function ListSalaries(arg1:usecase.ListSalariesInput):Promise<Array<domain.SalaryRecord>>;

export function PaySalary(arg1:string):Promise<void>;

export function RejectAdvance(arg1:string):Promise<domain.Advance>;

export function SetContext(arg1:context.Context):Promise<void>;
