// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApproveAdvance(arg1) {
  return window['go']['main']['SalaryService']['ApproveAdvance'](arg1);
}

export function CreateAdvance(arg1) {
  return window['go']['main']['SalaryService']['CreateAdvance'](arg1);
}

export function GenerateSalary(arg1) {
  return window['go']['main']['SalaryService']['GenerateSalary'](arg1);
}

export function GetSalary(arg1) {
  return window['go']['main']['SalaryService']['GetSalary'](arg1);
}

export function GetSalaryStats() {
  return window['go']['main']['SalaryService']['GetSalaryStats']();
}

export function ListAdvances(arg1) {
  return window['go']['main']['SalaryService']['ListAdvances'](arg1);
}

export function ListCycles(arg1) {
  return window['go']['main']['SalaryService']['ListCycles'](arg1);
}

export function ListSalaries(arg1) {
  return window['go']['main']['SalaryService']['ListSalaries'](arg1);
}

export function PaySalary(arg1) {
  return window['go']['main']['SalaryService']['PaySalary'](arg1);
}

export function RejectAdvance(arg1) {
  return window['go']['main']['SalaryService']['RejectAdvance'](arg1);
}

export function SetContext(arg1) {
  return window['go']['main']['SalaryService']['SetContext'](arg1);
}
