// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateService(arg1) {
  return window['go']['main']['ServiceService']['CreateService'](arg1);
}

export function DeleteService(arg1) {
  return window['go']['main']['ServiceService']['DeleteService'](arg1);
}

export function GetService(arg1) {
  return window['go']['main']['ServiceService']['GetService'](arg1);
}

export function GetServiceStats() {
  return window['go']['main']['ServiceService']['GetServiceStats']();
}

export function ListServices(arg1) {
  return window['go']['main']['ServiceService']['ListServices'](arg1);
}

export function SetContext(arg1) {
  return window['go']['main']['ServiceService']['SetContext'](arg1);
}

export function UpdateService(arg1, arg2) {
  return window['go']['main']['ServiceService']['UpdateService'](arg1, arg2);
}
