// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {usecase} from '../models';
import {domain} from '../models';
import {context} from '../models';

export function CreateService(arg1:usecase.CreateServiceInput):Promise<domain.Service>;

export function DeleteService(arg1:string):Promise<void>;

export function GetService(arg1:string):Promise<domain.Service>;

export function GetServiceStats():Promise<usecase.ServiceStats>;

export function ListServices(arg1:usecase.ListServiceInput):Promise<usecase.ListServiceOutput>;

export function SetContext(arg1:context.Context):Promise<void>;

export function UpdateService(arg1:string,arg2:usecase.UpdateServiceInput):Promise<domain.Service>;
