// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateStaff(arg1) {
  return window['go']['main']['StaffService']['CreateStaff'](arg1);
}

export function DeleteStaff(arg1) {
  return window['go']['main']['StaffService']['DeleteStaff'](arg1);
}

export function GetStaff(arg1) {
  return window['go']['main']['StaffService']['GetStaff'](arg1);
}

export function GetStaffStats() {
  return window['go']['main']['StaffService']['GetStaffStats']();
}

export function ListStaff(arg1) {
  return window['go']['main']['StaffService']['ListStaff'](arg1);
}

export function SetContext(arg1) {
  return window['go']['main']['StaffService']['SetContext'](arg1);
}

export function UpdateStaff(arg1, arg2) {
  return window['go']['main']['StaffService']['UpdateStaff'](arg1, arg2);
}
