// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {usecase} from '../models';
import {domain} from '../models';
import {context} from '../models';

export function CreateStaff(arg1:usecase.CreateStaffInput):Promise<domain.Staff>;

export function DeleteStaff(arg1:string):Promise<void>;

export function GetStaff(arg1:string):Promise<domain.Staff>;

export function GetStaffStats():Promise<usecase.StaffStats>;

export function ListStaff(arg1:usecase.ListStaffInput):Promise<usecase.ListStaffOutput>;

export function SetContext(arg1:context.Context):Promise<void>;

export function UpdateStaff(arg1:string,arg2:usecase.UpdateStaffInput):Promise<domain.Staff>;
