// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdate() {
  return window['go']['main']['UpdateService']['CheckForUpdate']();
}

export function DownloadUpdate() {
  return window['go']['main']['UpdateService']['DownloadUpdate']();
}

export function GetUpdateStatus() {
  return window['go']['main']['UpdateService']['GetUpdateStatus']();
}

export function InstallUpdate() {
  return window['go']['main']['UpdateService']['InstallUpdate']();
}

export function ListUpdateHistory(arg1, arg2) {
  return window['go']['main']['UpdateService']['ListUpdateHistory'](arg1, arg2);
}

export function SetContext(arg1) {
  return window['go']['main']['UpdateService']['SetContext'](arg1);
}
