// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';
import {context} from '../models';

export function CheckForUpdate():Promise<domain.UpdateStatus>;

export function DownloadUpdate():Promise<domain.UpdateRecord>;

export function GetUpdateStatus():Promise<domain.UpdateStatus>;

export function InstallUpdate():Promise<domain.UpdateRecord>;

export function ListUpdateHistory(arg1:number,arg2:number):Promise<Array<domain.UpdateRecord>>;

export function SetContext(arg1:context.Context):Promise<void>;
