// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateRule(arg1) {
  return window['go']['main']['WhatsAppService']['CreateRule'](arg1);
}

export function CreateTemplate(arg1) {
  return window['go']['main']['WhatsAppService']['CreateTemplate'](arg1);
}

export function DeleteRule(arg1) {
  return window['go']['main']['WhatsAppService']['DeleteRule'](arg1);
}

export function DeleteTemplate(arg1) {
  return window['go']['main']['WhatsAppService']['DeleteTemplate'](arg1);
}

export function GetWhatsAppStats() {
  return window['go']['main']['WhatsAppService']['GetWhatsAppStats']();
}

export function ListMessages(arg1, arg2, arg3) {
  return window['go']['main']['WhatsAppService']['ListMessages'](arg1, arg2, arg3);
}

export function ListRules() {
  return window['go']['main']['WhatsAppService']['ListRules']();
}

export function ListTemplates(arg1) {
  return window['go']['main']['WhatsAppService']['ListTemplates'](arg1);
}

export function SendMessage(arg1, arg2, arg3, arg4) {
  return window['go']['main']['WhatsAppService']['SendMessage'](arg1, arg2, arg3, arg4);
}

export function SetContext(arg1) {
  return window['go']['main']['WhatsAppService']['SetContext'](arg1);
}

export function UpdateRule(arg1) {
  return window['go']['main']['WhatsAppService']['UpdateRule'](arg1);
}

export function UpdateTemplate(arg1) {
  return window['go']['main']['WhatsAppService']['UpdateTemplate'](arg1);
}
