// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';
import {context} from '../models';

export function CreateRule(arg1:domain.AutomationRule):Promise<void>;

export function CreateTemplate(arg1:domain.WhatsAppTemplate):Promise<void>;

export function DeleteRule(arg1:string):Promise<void>;

export function DeleteTemplate(arg1:string):Promise<void>;

export function GetWhatsAppStats():Promise<domain.WAMessageStats>;

export function ListMessages(arg1:number,arg2:number,arg3:string):Promise<Array<domain.WhatsAppMessage>>;

export function ListRules():Promise<Array<domain.AutomationRule>>;

export function ListTemplates(arg1:string):Promise<Array<domain.WhatsAppTemplate>>;

export function SendMessage(arg1:string,arg2:string,arg3:string,arg4:Record<string, string>):Promise<domain.WhatsAppMessage>;

export function SetContext(arg1:context.Context):Promise<void>;

export function UpdateRule(arg1:domain.AutomationRule):Promise<void>;

export function UpdateTemplate(arg1:domain.WhatsAppTemplate):Promise<void>;
