// Wails runtime bindings - these are generated by Wails and available at runtime
// In dev mode with `wails dev`, the runtime is injected automatically
// In production, it's embedded in the binary

const BASE_URL = 'http://localhost:8080/api/v1'

export interface ApiResponse<T> {
  success: boolean
  data?: T
  error?: { message: string; code?: string }
  meta?: any
}

class ApiClient {
  private baseUrl: string

  constructor(baseUrl: string) {
    this.baseUrl = baseUrl
  }

  async get<T>(path: string): Promise<ApiResponse<T>> {
    const response = await fetch(`${this.baseUrl}${path}`)
    return response.json()
  }

  async post<T>(path: string, body?: unknown): Promise<ApiResponse<T>> {
    const response = await fetch(`${this.baseUrl}${path}`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: body ? JSON.stringify(body) : undefined,
    })
    return response.json()
  }

  async put<T>(path: string, body?: unknown): Promise<ApiResponse<T>> {
    const response = await fetch(`${this.baseUrl}${path}`, {
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      body: body ? JSON.stringify(body) : undefined,
    })
    return response.json()
  }

  async delete<T = void>(path: string): Promise<ApiResponse<T>> {
    const response = await fetch(`${this.baseUrl}${path}`, {
      method: 'DELETE',
    })
    return response.json()
  }
}

export const apiClient = new ApiClient(BASE_URL)

declare global {
  interface Window {
    go: {
      main: {
        App: {
          GetVersion: () => Promise<string>
          GetEnvironment: () => Promise<string>
        }
        StaffService: {
          ListStaff: (input: any) => Promise<any>
          GetStaff: (id: string) => Promise<any>
          CreateStaff: (input: any) => Promise<any>
          UpdateStaff: (id: string, input: any) => Promise<any>
          DeleteStaff: (id: string) => Promise<any>
          GetStaffStats: () => Promise<any>
        }
        CustomerService: {
          ListCustomers: (input: any) => Promise<any>
          GetCustomer: (id: string) => Promise<any>
          CreateCustomer: (input: any) => Promise<any>
          UpdateCustomer: (id: string, input: any) => Promise<any>
          DeleteCustomer: (id: string) => Promise<any>
          GetCustomerStats: () => Promise<any>
        }
        ServiceService: {
          ListServices: (input: any) => Promise<any>
          GetService: (id: string) => Promise<any>
          CreateService: (input: any) => Promise<any>
          UpdateService: (id: string, input: any) => Promise<any>
          DeleteService: (id: string) => Promise<any>
          GetServiceStats: () => Promise<any>
        }
        InvoiceService: {
          ListInvoices: (input: any) => Promise<any>
          GetInvoice: (id: string) => Promise<any>
          CreateInvoice: (input: any) => Promise<any>
          RecordPayment: (invoiceId: string, input: any) => Promise<any>
          GetInvoiceStats: () => Promise<any>
        }
        ExpenseService: {
          ListCategories: (activeOnly: boolean) => Promise<any>
          CreateCategory: (name: string, description: string) => Promise<any>
          UpdateCategory: (id: string, name: string, description: string, isActive: boolean) => Promise<any>
          CreateExpense: (input: any) => Promise<any>
          GetExpense: (id: string) => Promise<any>
          UpdateExpense: (id: string, input: any) => Promise<any>
          DeleteExpense: (id: string) => Promise<any>
          ListExpenses: (input: any) => Promise<any>
          GetExpenseStats: () => Promise<any>
          GetExpenseReport: (input: any) => Promise<any>
          GetProfitLoss: (input: any) => Promise<any>
          GetMonthlyTrend: (months: number) => Promise<any>
        }
        ProductService: {
          ListProducts: (input: any) => Promise<any>
          GetProduct: (id: string) => Promise<any>
          CreateProduct: (input: any) => Promise<any>
          UpdateProduct: (id: string, input: any) => Promise<any>
          DeleteProduct: (id: string) => Promise<any>
          AdjustStock: (input: any) => Promise<any>
          ListStockHistory: (input: any) => Promise<any>
          CreatePurchase: (input: any) => Promise<any>
          GetPurchase: (id: string) => Promise<any>
          ListPurchases: (input: any) => Promise<any>
          GetInventoryStats: () => Promise<any>
          GetLowStockProducts: () => Promise<any>
        }
        PerformanceService: {
          GetDailyPerformance: (input: any) => Promise<any>
          GetWeeklyPerformance: (input: any) => Promise<any>
          GetMonthlyPerformance: (input: any) => Promise<any>
          GetTopPerformers: (input: any) => Promise<any>
          GetRevenueTrend: (dateFrom: string, dateTo: string) => Promise<any>
          GetStaffRevenueTrend: (staffId: string, dateFrom: string, dateTo: string) => Promise<any>
          GetPerformanceStats: () => Promise<any>
          GetStaffPerformance: (staffId: string, dateFrom: string, dateTo: string) => Promise<any>
        }
        CommissionService: {
          CreateRule: (input: any) => Promise<any>
          GetRule: (id: string) => Promise<any>
          ListRules: (input: any) => Promise<any>
          UpdateRule: (id: string, input: any) => Promise<any>
          DeleteRule: (id: string) => Promise<any>
          GetStaffCommission: (input: any) => Promise<any>
          GetMonthlyCommission: (input: any) => Promise<any>
          GetCommissionStats: () => Promise<any>
        }
        SalaryService: {
          GenerateSalary: (input: any) => Promise<any>
          GetSalary: (id: string) => Promise<any>
          ListSalaries: (input: any) => Promise<any>
          PaySalary: (id: string) => Promise<any>
          ListCycles: (year: number) => Promise<any>
          CreateAdvance: (input: any) => Promise<any>
          ApproveAdvance: (id: string) => Promise<any>
          RejectAdvance: (id: string) => Promise<any>
          ListAdvances: (input: any) => Promise<any>
          GetSalaryStats: () => Promise<any>
        }
        AnalyticsService: {
          GetDashboard: () => Promise<any>
          GetKPIs: (dateFrom: string, dateTo: string) => Promise<any>
          GetRevenueReport: (dateFrom: string, dateTo: string, groupBy: string) => Promise<any>
          GetCustomerReport: (dateFrom: string, dateTo: string) => Promise<any>
          GetStaffReport: (dateFrom: string, dateTo: string) => Promise<any>
          GetServiceReport: (dateFrom: string, dateTo: string) => Promise<any>
          GetExpenseAnalytics: (dateFrom: string, dateTo: string) => Promise<any>
          GetInventoryReport: () => Promise<any>
          GetProfitLossReport: (dateFrom: string, dateTo: string, groupBy: string) => Promise<any>
        }
        BackupService: {
          CreateBackup: (backupType: string) => Promise<any>
          VerifyBackup: (id: string) => Promise<any>
          RestoreBackup: (id: string, notes: string) => Promise<any>
          ListBackups: (page: number, perPage: number) => Promise<any>
          ListRestores: (page: number, perPage: number) => Promise<any>
          GetBackupStats: () => Promise<any>
          DeleteBackup: (id: string) => Promise<any>
        }
        LicenseService: {
          GetStatus: () => Promise<any>
          Validate: () => Promise<any>
          Activate: (key: string, customerName: string, salonName: string) => Promise<any>
          Renew: (key: string) => Promise<any>
          ListEvents: (page: number, perPage: number) => Promise<any>
        }
        UpdateService: {
          CheckForUpdate: () => Promise<any>
          DownloadUpdate: () => Promise<any>
          InstallUpdate: () => Promise<any>
          GetUpdateStatus: () => Promise<any>
          ListUpdateHistory: (page: number, perPage: number) => Promise<any>
        }
        ImportService: {
          Upload: (fileName: string, filePath: string, targetEntity: string) => Promise<any>
          Validate: (jobId: string, mappings: any[]) => Promise<any>
          Process: (jobId: string) => Promise<any>
          ListJobs: (page: number, perPage: number) => Promise<any>
          GetJob: (id: string) => Promise<any>
          ListLogs: (jobId: string, status: string, page: number, perPage: number) => Promise<any>
        }
        GSTService: {
          GetSettings: () => Promise<any>
          SaveSettings: (settings: any) => Promise<any>
          ListTaxRates: (category: string) => Promise<any>
          CreateTaxRate: (rate: any) => Promise<any>
          UpdateTaxRate: (rate: any) => Promise<any>
          DeleteTaxRate: (id: string) => Promise<any>
          GetReport: (filter: any) => Promise<any>
        }
        PrinterService: {
          GetSettings: () => Promise<any>
          SaveSettings: (settings: any) => Promise<any>
          PrintInvoice: (data: any) => Promise<any>
          PrintReceipt: (data: any) => Promise<any>
          PrintTest: () => Promise<any>
          ListPrintJobs: (limit: number, offset: number) => Promise<any>
          GetPrintJob: (id: string) => Promise<any>
        }
        AppointmentService: {
          CreateAppointment: (appt: any, services: any[]) => Promise<any>
          UpdateAppointment: (appt: any, services: any[]) => Promise<any>
          UpdateAppointmentStatus: (id: string, status: string, note: string) => Promise<any>
          DeleteAppointment: (id: string) => Promise<any>
          GetAppointment: (id: string) => Promise<any>
          ListAppointments: (filter: any) => Promise<any>
          GetAppointmentHistory: (id: string) => Promise<any>
        }
        WhatsAppService: {
          CreateTemplate: (tmpl: any) => Promise<any>
          UpdateTemplate: (tmpl: any) => Promise<any>
          DeleteTemplate: (id: string) => Promise<any>
          ListTemplates: (category: string) => Promise<any>
          SendMessage: (templateId: string, phone: string, name: string, variables: Record<string, string>) => Promise<any>
          ListMessages: (limit: number, offset: number, status: string) => Promise<any>
          GetWhatsAppStats: () => Promise<any>
          CreateRule: (rule: any) => Promise<any>
          UpdateRule: (rule: any) => Promise<any>
          DeleteRule: (id: string) => Promise<any>
          ListRules: () => Promise<any>
        }
        MembershipService: {
          CreatePlan: (plan: any, services: any[]) => Promise<any>
          UpdatePlan: (plan: any, services: any[]) => Promise<any>
          DeletePlan: (id: string) => Promise<any>
          GetPlan: (id: string) => Promise<any>
          ListPlans: (planType: string) => Promise<any>
          SellPlan: (customerId: string, planId: string, amountPaid: number) => Promise<any>
          UseSession: (subscriptionId: string) => Promise<any>
          ListSubscriptions: (customerId: string, status: string, limit: number, offset: number) => Promise<any>
          GetMembershipStats: () => Promise<any>
        }
        CloudBackupService: {
          GetConfig: () => Promise<any>
          SaveConfig: (cfg: any) => Promise<any>
          TestConnection: () => Promise<any>
          BackupNow: () => Promise<any>
          Restore: (historyId: string) => Promise<any>
          ListHistory: (limit: number, offset: number) => Promise<any>
          GetCloudBackupStats: () => Promise<any>
        }
      }
    }
  }
}
